# Activar consola H2
spring.h2.console.enabled=true

# Configurar datasource en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Configurar JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.enabled=true

# Spring Batch
spring.batch.job.enabled=true
spring.batch.job.name=importStudentsJob
logging.level.org.springframework.batch=DEBUG

# Circuit Breaker (Resilience4j)
resilience4j.circuitbreaker.instances.studentsCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.studentsCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.studentsCB.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.studentsCB.permittedNumberOfCallsInHalfOpenState=2

# Incrementar el timeout del flux para que nunca de timeout
#spring.mvc.async.request-timeout=60000

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# TraceID
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg [traceId=%X{traceId}]%n
