# Activar consola H2
spring.h2.console.enabled=true

# Configurar datasource en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Configurar JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.enabled=true

# Spring Batch
spring.batch.job.enabled=true
spring.batch.job.name=importStudentsJob
logging.level.org.springframework.batch=DEBUG
